### ISSUE TITLE
Popup always is about:blank

### ISSUE THREAD

**Issue by oliviermattei** [dahliacreative/sharetastic#8]
I'm using the master branch,

meta property="og:title" content="Title for your page" />
meta property="og:description" content="Description for your page" />
meta property="og:url" content="url" />
meta property="og:image" content="image" />

Sharetastic initialisation:
$('.sharetastic').sharetastic({
        popup: true,
        services: {
            linkedin: false,
            googleplus: false,
            flickr: false,
            tumblr: false,
            email: false,
            print: false
        }
    });

div class="sharetastic" data-title="title" data-description="desc" data-image="url"></div>

All adblocker are down, no error in console.

**Comment by dahliacreative** [comment]
can you do a jsbin or codepen with your set up so I can try and debug it please?

**Comment by ghost** [comment]
Same here.. cannot get it to work. Was this ever resolved?

**Comment by trinvh** [comment]
The same. Only works with email button.
Link anchor seems correct. However when clicking the displayed popup always point to about:blank

**Comment by trinvh** [comment]
I fixed this by myself.
For anyone else that sees this problem. Search in the code for:

````self.popup(e.target.getAttribute('href'), 500, 300)````

with

````self.popup(service.href, 500, 300)````

Happy coding!

**Comment by dahliacreative** [comment]
Fixed in v.2.0.5
